name: tull
channels:
  - conda-forge
dependencies:
  - python=3.11
  - conda-forge::ffmpeg
  - conda-forge::opencv
  - scikit-fmm

  - pip
  - pip:
      - matplotlib
      - numpy
      - Pillow
      - click
      - rich
      - strenum
      - stringcase

      - black

      - -e .
